"""empty message

Revision ID: 03735e823e49
Revises: a62be209250d
Create Date: 2024-05-25 15:28:50.997046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03735e823e49'
down_revision = 'a62be209250d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios_preferencias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome_genero', sa.String(length=100), nullable=False),
    sa.Column('estado_preferencia', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios_preferencias')
    # ### end Alembic commands ###
