"""empty message

Revision ID: 537d5aa584a8
Revises: ed7af4717fad
Create Date: 2024-04-16 16:04:12.751900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537d5aa584a8'
down_revision = 'ed7af4717fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios_listas',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.Column('tipo_lista', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('lista_id')
    )
    op.create_table('listas_livros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.Column('livro_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['lista_id'], ['usuarios_listas.lista_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listas_livros')
    op.drop_table('usuarios_listas')
    # ### end Alembic commands ###
