"""empty message

Revision ID: a62be209250d
Revises: 537d5aa584a8
Create Date: 2024-05-20 14:41:35.781663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a62be209250d'
down_revision = '537d5aa584a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listas_livros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota_livro', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listas_livros', schema=None) as batch_op:
        batch_op.drop_column('nota_livro')

    # ### end Alembic commands ###
