"""empty message

Revision ID: ed7af4717fad
Revises: 070537554063
Create Date: 2024-03-18 16:22:14.703279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7af4717fad'
down_revision = '070537554063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livro_genero',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_livro', sa.String(length=100), nullable=False),
    sa.Column('nome_genero', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livro_genero')
    # ### end Alembic commands ###
